// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bimmgsncdzqhkbscjqyz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpbW1nc25jZHpxaGtic2NqcXl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NzY2MjMsImV4cCI6MjA2NjM1MjYyM30.U9XVrhvPrHxz3kYNEiLXuA-ERvijd2NM4dZg9spaLhw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);